### PR TITLE
Mm feature/navbar layout

### LINKED ISSUE #31: Design Navbar layout (Mobile and Desktop)
- [x]  Mobile nav bar version is similar to the one we currently have.
- [x]  Desktop nav bar is on the top as figma design. 
- [x]  Remove manage list page since we moved everything out of it.

### PR DESCRIPTION
**Pull request by marshjaja**
## Description
This PR introduces a fully responsive navigation system for both desktop and tablet/mobile devices.
An active link class has been applied to highlight the current page the user is on, along with hover states for the links and icons.
Additionally, a light and dark mode toggle has been implemented, allowing users to switch between these two themes.
This enhances the user experience by ensuring the navigation is intuitive across devices and provides flexibility in user interface preferences.

## Related Issue
Closes #31 

## Acceptance Criteria

- [x]  Mobile nav bar version is similar to the one we currently have.
- [x]  Desktop nav bar is on the top as Figma design. 
- [x]  Remove manage list page since we moved everything out of it. 

## Type of Changes

`feature`
`enhancement` 

### Before

Screenshot 2024-10-05 at 17 11 02

Screenshot 2024-10-05 at 16 37 59
Screenshot 2024-10-05 at 16 38 27

#### Favicon

Screenshot 2024-10-05 at 16 53 12

#### Desktop Light mode
Screenshot 2024-10-05 at 16 43 46

Screenshot 2024-10-05 at 16 46 09

#### Desktop Dark mode
Screenshot 2024-10-05 at 16 45 22

Screenshot 2024-10-05 at 16 44 08

#### Mobile Light mode
Screenshot 2024-10-05 at 16 47 07
Screenshot 2024-10-05 at 16 47 18

#### Mobile Dark mode

Screenshot 2024-10-05 at 16 47 34
Screenshot 2024-10-05 at 16 47 46

## Testing Steps / QA Criteria

- Do a `git pull` and `git checkout mm-feature/navbar-layout` 
- After switching you can see the responsive navbar displayed. You can switch between desktop and tablet/mobile views to observe the different layouts
- You can also toggle between Light mode and Dark mode to test the theme-switching functionality.

### CODE REVIEW

**Review by joriordan332 — APPROVED** [review]
So good! Love that addition of the shopping cart icon showing on the tab, well done!

**Review by Hudamabkhoot — CHANGES_REQUESTED** [review]
Well done @marshjaja it looks amazing! 🙌 I only have a few comments

- I believe the logo is a bit big for desktop and too big for mobile.  
- The nav bar active and hover state are the same color so if i'm on home and i hover over list they both look active.
- The mobile nav bar doesn't have a background so if the list is longer it wont be that visible.

**Comment by marshjaja** [comment]
@Hudamabkhoot  good spots, thank you!👏🏾 I have implemented your requested changes. Fingers crossed and and may the power be with us when we go and do our merges🥲😅

**Review by Hudamabkhoot — APPROVED** [review]
Everything looks great now! We are going to do well! 💪

**Pull request merged**
