### PR TITLE
Feat: Delete lists

### LINKED ISSUE #36: Adding a delete button to each list.
> Adding a delete button to each list.

It could be complicated, better left to the end

_Originally posted by @redapy in https://github.com/the-collab-lab/tcl-79-smart-shopping-list/issues/32#issuecomment-2381413378_

### PR DESCRIPTION
**Pull request by Wyna-7**
## Description

Users can now delete lists from the home page. They are only allowed to delete lists they have created themselves, the button is disabled for lists that have been shared with the logged user.
Deleting a list removes the corresponding document in the user's collecton, and the reference to it in the sharedLists field array.

## Related Issue

Closes #36 

## Acceptance Criteria

- [x] The delete button is active for user created lists, and inactive for shared ones.
- [x] When clicked, the delete button immediately removes the list from Your Lists.
- [x] After a list is deleted, it disappears from the user collection and from the sharedLists field array. 

## Type of Changes

`feat` 

### Before

Pretty much the same.

### After
Disabled button is now grey.
image

No list selected
image

## Testing Steps / QA Criteria

- Do a `git pull` and then `git checkout qg-feat-delete-list`
- Run `npm start` to open GrocerEase
- Create a few test lists, then click their delete buttons to delete them.
- After deletion, the lists should be gone from both your user collection and your sharedLists array.
- If you delete the list that you had selected, navigating to the `Lists` page should show the no list selected text.

### CODE REVIEW

**Review by joriordan332 — APPROVED** [review]
This is a brilliant feature! Well done

**Review by Hudamabkhoot — CHANGES_REQUESTED** [review]
Well done @Wyna-7 really that was a tough one! 🙌  just one thing i think adding an alert dialog to check with the user before deleting a list would be good.

**Comment by marshjaja** [comment]
Well done @Wyna-7!🤾🏾‍♀️ Yeah I  agree with Huda, to add a prompt if the user is really sure they want to delete that list

**Review by Hudamabkhoot — APPROVED** [review]
Great work 👏 just one thing make sure the delete dialog color scheme match the list page one before merging.

**Pull request merged**
